name: Deploy to S3

# Dispara o workflow quando um push for feito na branch main
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://<bucket-mateus> --delete --region <us-east-2>
