name: Build and Deploy Docker Image

# Dispara o workflow quando um push for feito na branch main
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: <nome_do_usuario>/<nome_da_imagem>:latest
        dockerfile: Dockerfile
    - name: Deploy Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker-compose pull
          docker-compose up -d